In [ ]:
#Name:Aryan Mahesh Patil
#Roll No:51
#Subject: ML
#Exp no:1

SyntaxError: invalid syntax (ipython-input-2604903973.py, line 1)

In [25]:
import numpy as np

In [26]:
# -------------------------
# 1. Array Creation
# -------------------------
arr1 = np.array([1, 2, 3, 4, 5])
print("Array from list:", arr1)

arr2 = np.array([[1,2,3],[4,5,6]])
print("2D Array:\n", arr2)

arr_arange = np.arange(0, 10, 2)
print("arange array:", arr_arange)

arr_linspace = np.linspace(0, 1, 5)
print("linspace array:", arr_linspace)

arr_zeros = np.zeros((2,3))
print("zeros array:\n", arr_zeros)

arr_ones = np.ones((3,2))
print("ones array:\n", arr_ones)
arr_eye = np.eye(3)
print("Identity matrix:\n", arr_eye)

Array from list: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
arange array: [0 2 4 6 8]
linspace array: [0.   0.25 0.5  0.75 1.  ]
zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
# -------------------------
# 2. Array Attributes
# -------------------------
print("Shape of arr2:", arr2.shape)
print("Size of arr2:", arr2.size)
print("Number of dimensions:", arr2.ndim)
print("Data type:", arr2.dtype)
print("Item size (bytes):", arr2.itemsize)

Shape of arr2: (2, 3)
Size of arr2: 6
Number of dimensions: 2
Data type: int64
Item size (bytes): 8


In [28]:
# -------------------------
# 3. Indexing and Slicing
# -------------------------
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)
print("Index 2:", arr[2])
print("Last element:", arr[-1])
print("Slice 1:4:", arr[1:4])

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array:\n", arr2d)
print("First row:", arr2d[0,:])
print("Second column:", arr2d[:,1])
print("Submatrix:\n", arr2d[0:2,1:3])

Original array: [10 20 30 40 50]
Index 2: 30
Last element: 50
Slice 1:4: [20 30 40]
2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First row: [1 2 3]
Second column: [2 5 8]
Submatrix:
 [[2 3]
 [5 6]]


In [29]:
# -------------------------
# 4. Basic Operations
# -------------------------
a = np.array([1,2,3])
b = np.array([4,5,6])

print("a+b:",a+b)
print("a-b:",a-b)
print("a*b:",a*b)
print("a/b:",a/b)
print("a**2:",a**2)

c=np.array([[1,2,3],[4,5,6]])
d=np.array([1,1,1])
print("Broadcasting sum:\n",c+d)

a+b: [5 7 9]
a-b: [-3 -3 -3]
a*b: [ 4 10 18]
a/b: [0.25 0.4  0.5 ]
a**2: [1 4 9]
Broadcasting sum:
 [[2 3 4]
 [5 6 7]]


In [30]:
#------------------------------
#5.Universal Functions(ufunes)
#----------------------------
arr=np.array([1,4,9,16])
print("Sqrt:",np.sqrt(arr))
print("Exp:",np.exp(arr))
print("Sin:",np.sin(arr))
print("Cos:",np.cos(arr))

Sqrt: [1. 2. 3. 4.]
Exp: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Sin: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]
Cos: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948]


In [31]:
#------------------------------
#6.Aggregation Function
#-----------------------------
arr=np.array([[1,2,3],[4,5,6]])
print("Sum:",np.sum(arr))
print("Sum axis 0:",np.sum(arr,axis=0))
print("Sum axis 1:",np.sum(arr,axis=1))
print("Mean:",np.mean(arr))
print("Max:",np.max(arr))
print("Min:", np.min(arr))
print("Argmax:", np.argmax(arr))
print("Argmin:", np.argmin(arr))
print("Standard deviation:", np.std(arr))
print("Variance:", np.var(arr))

Sum: 21
Sum axis 0: [5 7 9]
Sum axis 1: [ 6 15]
Mean: 3.5
Max: 6
Min: 1
Argmax: 5
Argmin: 0
Standard deviation: 1.707825127659933
Variance: 2.9166666666666665


In [32]:
#----------------------------
#Reshaping and Flattening
#----------------------------
arr=np.arange(12)
print("Original array:",arr)
arr_reshaped=arr.reshape(3,4)
print("Reshaped array:\n",arr_reshaped)
arr_flattened=arr_reshaped.flatten()
print("Flattened array:",arr_flattened)
arr_transposed=arr_reshaped.transpose()
print("Transposed array:\n",arr_transposed)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [33]:
#------------------------
#Stacking and Splitting
#------------------------
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Stacking horizontally:",np.hstack((a,b)))
print("Stacking vertically:",np.vstack((a,b)))

arr=np.arange(9)
print("Original array:",arr)
print("Split into 3 parts:",np.split(arr,3))

Stacking horizontally: [1 2 3 4 5 6]
Stacking vertically: [[1 2 3]
 [4 5 6]]
Original array: [0 1 2 3 4 5 6 7 8]
Split into 3 parts: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [34]:
#---------------------------
#9.Copy vs View
#---------------------------
arr=np.array([1,2,3])
arr_copy=arr.copy()
arr_view=arr.view()
arr[0]=10
print("Original after view change:",arr_view)
print("Original after copy change:",arr_copy)

Original after view change: [10  2  3]
Original after copy change: [1 2 3]


In [35]:
#----------------------------------------
#10.Boolean Indexing & Fancy Indexing
#----------------------------------------
arr = np.array([10,20,30,40,50])
print("Elements > 25:", arr[arr>25])
indices = [0,2,4]
print("Fancy indexing:", arr[indices])

Elements > 25: [30 40 50]
Fancy indexing: [10 30 50]


In [36]:
#---------------------------------------
#11.Random Numbers
#--------------------------------------
rand_arr=np.random.rand(3,3)
print("Random array:\n",rand_arr)

rand_int=np.random.randint(1,10,5)
print("Random integer array:\n",rand_int)

normal_arr=np.random.randn(3,3)
print("Normal distribution array:\n",normal_arr)

Random array:
 [[0.59269508 0.27314901 0.1878989 ]
 [0.87472182 0.20763016 0.04676298]
 [0.95417888 0.03476563 0.44563166]]
Random integer array:
 [1 3 8 2 7]
Normal distribution array:
 [[-1.05781909  1.89038326  0.36455039]
 [ 0.32905788  0.95606963 -1.11024951]
 [ 0.39952781  0.56558135  0.15067324]]


In [37]:
#--------------------------------
#12. Linear Algebra Functions
# --------------------------------
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Matrix multiplication:\n", np.dot(A,B))
print("Matrix determinant:", np.linalg.det(A))
print("Matrix inverse:\n", np.linalg.inv(A))
print("Eigenvalues and Eigenvectors:\n", np.linalg.eig(A))

Matrix multiplication:
 [[19 22]
 [43 50]]
Matrix determinant: -2.0000000000000004
Matrix inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues and Eigenvectors:
 EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [38]:
# -------------------------
# 13. Saving and Loading Arrays
# -------------------------
np.save('array.npy', arr)
loaded_arr = np.load('array.npy')
print("Loaded array:", loaded_arr)

print("\nAll major NumPy functions executed successfully!")

Loaded array: [10 20 30 40 50]

All major NumPy functions executed successfully!
